<?php

if(isset($_POST))
{
    print_r($_POST);
}

?>

<!DOCTYPE html>   
<html>   
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">  
<title> Login Page </title>  
<style>   
Body {  
  font-family: Calibri, Helvetica, sans-serif;  
  background-color: pink;  
}  
button {   
       background-color: #4CAF50;   
       width: 100%;  
        color: orange;   
        padding: 15px;   
        margin: 10px 0px;   
        border: none;   
        cursor: pointer;   
         }   
 form {   
        border: 3px solid #f1f1f1;   
    }   
 input[type=text], input[type=password] {   
        width: 25%;   
        margin: 8px 0;        
        padding: 8px 20px;   
        display: inline-block;   
        border: 2px solid green;   
        box-sizing: border-box;   
    }  
button[type=submit] {   
        width: 10%;   
        margin: 8px 0;  
        margin-left : 5%;
        padding: 12px 20px;   
        display: inline-block;   
        border: 2px solid green;   
        box-sizing: border-box;   
    }
 button:hover {   
        opacity: 0.7;   
    }   
  .cancelbtn {   
        width: auto;   
        padding: 10px 18px;  
        margin: 10px 5px;  
    }   
        
     
 .container {   
        padding: 25px;   
        background-color: lightblue;  
    }   
</style>   
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script type="text/javascript">$(document).ready(function() {
var max_fields      = 10; //maximum input boxes allowed
var wrapper   		= $(".input_fields_wrap"); //Fields wrapper
var add_button      = $(".add_field_button"); //Add button ID

var x = 1; //initlal text box count
$(add_button).click(function(e){ //on add input button click
e.preventDefault();
    if(x < max_fields){ //max input box allowed
        x++; //text box increment
        $(wrapper).append('<div class="input-group mb-3" ><input placeholder="Enter Label" id="1" type="text" name="label[]" class="form-control"><input placeholder="Enter Value" id="1" type="text" name="value[]" class="form-control">   <button class="btn btn-outline-danger remove_field" type="button">Remove</button></div>'); //add input box
        // $(wrapper).append('<div class="input-group mb-3" id="1"><input placeholder="Enter Value" type="text" name="mytext[]" class="form-control"><div class="input-group-append"><button class="btn btn-outline-danger remove_field" type="button">Remove</button></div></div>'); //add input box
    }
});

$(wrapper).on("click",".remove_field", function(e){ //user click on remove text
    e.preventDefault(); 
    $(this).parent('div').remove();
     x--;
    })
});
</script>
</head>    
<body>    
    <center> <h1> Form </h1> </center>   
    <form method="post" action="/add/addtodb">  
        <div class="container">   
            <label>Name : </label>   
            <input type="text" placeholder="Enter Username" name="username" required>  
            <br>
            <label>Category : </label>   
            <input type="text" placeholder="Enter Category" name="category" required>  
            <br>
            <label>price : </label>   
            <input type="text" placeholder="Enter Price" name="price" required>  
            <br>
            <label>Stock : </label>   
            <input type="text" placeholder="Enter Stock" name="stock" required>  
            <br>
            <button type="submit">Add Product</button>   
            
        
        



      
    <div class="col-md-4"></div>
    <div class="col-md-4">
            <div class="input_fields_wrap">
            <button class="add_field_button btn-primary" >Additional Fields</button>
        </div>
    </div>
    <div class="col-md-4"></div>


        </div>
    </form>     
</body>     
</html>  