<?php


// foreach($edit_data['_id'] as $k)
// {
//     print_r($k);
// }
?>


<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Login Page </title>
    <style>
        Body {
            font-family: Calibri, Helvetica, sans-serif;
            background-color: pink;
        }

        button {
            background-color: #4CAF50;
            width: 100%;
            color: orange;
            padding: 15px;
            margin: 10px 0px;
            border: none;
            cursor: pointer;
        }

        form {
            border: 3px solid #f1f1f1;
        }

        input[type=text],
        input[type=password] {
            width: 25%;
            margin: 8px 0;
            padding: 8px 20px;
            display: inline-block;
            border: 2px solid green;
            box-sizing: border-box;
        }

        button[type=submit] {
            width: 10%;
            margin: 8px 0;
            margin-left: 5%;
            padding: 12px 20px;
            display: inline-block;
            border: 2px solid green;
            box-sizing: border-box;
        }

        button:hover {
            opacity: 0.7;
        }

        .cancelbtn {
            width: auto;
            padding: 10px 18px;
            margin: 10px 5px;
        }


        .container {
            padding: 25px;
            background-color: lightblue;
        }
    </style>

</head>

<body>
    <center>
        <h1> Edit Form </h1>
    </center>
    <form method="post" action="/add/update">
        <div class="container">
            <input type="hidden" placeholder="Enter Username" name="id" value="<?php foreach ($edit_data['_id'] as $k) {
                                                                                    print_r($k);
                                                                                }  ?>">
            <label>Name : </label>
            <input type="text" placeholder="Enter Username" name="name" value="<?php print_r($edit_data['username']); ?>">
            <br>
            <label>Category : </label>
            <input type="text" placeholder="Enter Category" name="category" value="<?php print_r($edit_data['category']); ?>">
            <br>
           
            <label>price : </label>
            <input type="text" placeholder="Enter Price" name="price" value="<?php print_r($edit_data['price']); ?>">
            <br>
            <label>Stock : </label>
            <input type="text" placeholder="Enter Stock" name="stock" value="<?php print_r($edit_data['stock']); ?>">
            <br><br>

            <h4>Additional Field</h4> 
            <?php
            foreach ($edit_data['myarray'] as $a) {
                echo "label: <input type='text' name='label[]' value=" . $a['label'] . "><br><br>";
                echo "value: <input type='text' name='value[]' value=" . $a['value'] . "><br><br>";
            }
            ?>

            <br>



            <h4>Additional Variation</h4> 
            <?php
            foreach ($edit_data['myarrayV'] as $a) {
                echo "label: <input type='text' name='labelv[]' value=" . $a['labelv'] . "><br><br>";
                echo "value: <input type='text' name='valuev[]' value=" . $a['valuev'] . "><br><br>";
                echo "field: <input type='text' name='fieldv[]' value=" . $a['fieldv'] . "><br><br>";
            }
            ?>

            <br>
            <button type="submit">Submit</button>


        </div>
    </form>
</body>

</html>