
<!DOCTYPE html>   
<html>   
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">  
<title> Login Page </title>  
<style>   
Body {  
  font-family: Calibri, Helvetica, sans-serif;  
  background-color: pink;  
}  
button {   
       background-color: #4CAF50;   
       width: 100%;  
        color: orange;   
        padding: 15px;   
        margin: 10px 0px;   
        border: none;   
        cursor: pointer;   
         }   
 form {   
        border: 3px solid #f1f1f1;   
    }   
 input[type=text], input[type=password] {   
        width: 25%;   
        margin: 8px 0;        
        padding: 8px 20px;   
        display: inline-block;   
        border: 2px solid green;   
        box-sizing: border-box;   
    }  
button[type=submit] {   
        width: 10%;   
        margin: 8px 0;  
        margin-left : 5%;
        padding: 12px 20px;   
        display: inline-block;   
        border: 2px solid green;   
        box-sizing: border-box;   
    }
 button:hover {   
        opacity: 0.7;   
    }   
  .cancelbtn {   
        width: auto;   
        padding: 10px 18px;  
        margin: 10px 5px;  
    }   
        
     
 .container {   
        padding: 25px;   
        background-color: lightblue;  
    }   
</style>   

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- <script type="text/javascipt" src="jquery-3.6.0.js" ></script> -->
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script type="text/javascript">
    // $(document).ready(function(type){
    //     function loadData(){ 
    //     $.ajax({
    //         url : "aakash.phtml",
    //         type : "POST",
    //         data : {c : c},
    //         success :function(data){
    //             $("#dropdownMenuButton").append(data);

    //         }
    //     });
    //     }
    //     loadData();
    //     $("#dropdownMenuButton").on("change",function(){
    //         var c =$("#dropdownMenuButton").val();
    //     })
    // })
    $(document).ready(function(){
    $('.container').on('change','#variation', function(){
        var cid = $(this).val();
        console.log(cid);
      //  if(cid){
            $.ajax({
                type:'POST',
                url:'/order/ajax',
                data: {'cid' : cid},
                success:function(html){
                    $('#av').html(html);
         
                }
            }); 
      //  }
        // else{
        //     $('#state').html('<option value="">Select country first</option>');
          
        // }
    });
    
    
});
    </script>
</head>    
<body>    
    <center> <h1> Form </h1> </center>   
    <form method="post" action="">  
        <div class="container">   
            <label>Customer Name : </label>   
            <input type="text" placeholder="Enter Customer" name="cname" required>  
            <br>
            <label>Quantity : </label>   
            <input type="text" placeholder="Enter Quantity" name="cquantity" required>  
            <br>
            <!-- <div class="dropdown d-inline-block">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown button
            </button>

            <div class="dropdown-menu w-100 " arialabelledby="dropdownMenuButton">
                <?php
                // foreach($data as $k)
                // {
                   // echo '<a class="dropdown-item" href="">'.$k['username'].'</a>';
              //  } 
                ?>
              
            </div>
</div> -->

<label for="cars">Choose variation:</label>

<select name="variation" id="variation">
<?php
        foreach($data as $k)
        {
            // echo '<a class="dropdown-item" href="">'.$k['username'].'</a>';
            echo '<option value='.$k['_id'].' >'.$k['username'].'</option>';
        } 
                ?>
                


</select>
<br>
<p id = "av"></p>
<p id = "av1"></p>
                            
            <button type="submit" name="submit" >Add Product</button>   
            
        
        



      





        </div>
    </form>     
</body>     
</html>  